#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.5.1
# from Racc grammar file "".
#

require 'racc/parser.rb'

require 'strscan'

module EDTF
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 437)

  @defaults = {
    :level => 2,
    :debug => false
  }.freeze

  class << self; attr_reader :defaults; end

  attr_reader :options

  def initialize(options = {})
    @options = Parser.defaults.merge(options)
  end

  def debug?
    !!(options[:debug] || ENV['DEBUG'])
  end

  def parse(input)
    parse!(input)
  rescue => e
    warn e.message if debug?
    nil
  end

  def parse!(input)
    @yydebug = debug?
    @src = StringScanner.new(input)
    do_parse
  end

  def on_error(tid, value, stack)
    raise ArgumentError,
      "failed to parse date: unexpected '#{value}' at #{stack.inspect}"
  end

  def apply_uncertainty(date, uncertainty, scope = nil)
    uncertainty.each do |u|
      scope.nil? ? date.send(u) : date.send(u, scope)
    end
    date
  end

  alias uoa apply_uncertainty

  def next_token
    case
    when @src.eos?
      nil
    # when @src.scan(/\s+/)
      # ignore whitespace
    when @src.scan(/\(/)
      ['(', @src.matched]
    # when @src.scan(/\)\?~-/)
    #   [:PUA, [:uncertain!, :approximate!]]
    # when @src.scan(/\)\?-/)
    #   [:PUA, [:uncertain!]]
    # when @src.scan(/\)~-/)
    #   [:PUA, [:approximate!]]
    when @src.scan(/\)/)
      [')', @src.matched]
    when @src.scan(/\[/)
      ['[', @src.matched]
    when @src.scan(/\]/)
      [']', @src.matched]
    when @src.scan(/\{/)
      ['{', @src.matched]
    when @src.scan(/\}/)
      ['}', @src.matched]
    when @src.scan(/T/)
      [:T, @src.matched]
    when @src.scan(/Z/)
      [:Z, @src.matched]
    when @src.scan(/\?~/)
      [:UA, [:uncertain!, :approximate!]]
    when @src.scan(/\?/)
      [:UA, [:uncertain!]]
    when @src.scan(/~/)
      [:UA, [:approximate!]]
    when @src.scan(/open/i)
      [:OPEN, :open]
    when @src.scan(/unkn?own/i) # matches 'unkown' typo too
      [:UNKNOWN, :unknown]
    when @src.scan(/X/)
      [:X, @src.matched]
    when @src.scan(/Y/)
      [:LONGYEAR, @src.matched]
    when @src.scan(/E/)
      [:E, @src.matched]
    when @src.scan(/\+/)
      ['+', @src.matched]
    when @src.scan(/-\(/)
      ['-(', @src.matched]
    when @src.scan(/-/)
      ['-', @src.matched]
    when @src.scan(/:/)
      [':', @src.matched]
    when @src.scan(/\//)
      ['/', @src.matched]
    when @src.scan(/\s*\.\.\s*/)
      [:DOTS, '..']
    when @src.scan(/\s*,\s*/)
      [',', ',']
    when @src.scan(/\^\w+/)
      ['^', @src.matched[1..-1]]
    when @src.scan(/\d/)
      [@src.matched, @src.matched.to_i]
    else @src.scan(/./)
      [:UNMATCHED, @src.rest]
    end
  end


# -*- racc -*-
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    18,    27,    28,    29,   113,   113,    59,   114,   114,    45,
    47,    42,    11,    53,    44,    57,    46,    54,    35,    60,
    36,    56,   127,    38,   -53,    64,    48,    49,    50,    51,
    52,    45,    47,    42,    58,   -51,    44,    55,    46,   146,
    57,    65,   165,    66,   204,    67,   145,    68,    48,    49,
    50,    51,    52,    45,    47,    42,   166,   167,    44,    58,
    46,   103,   113,   105,   -68,   114,   106,    27,    28,   -69,
    48,    49,    50,    51,    52,    45,    47,    42,    11,    87,
    44,    98,    46,    45,    47,    42,    11,   130,    44,    38,
    46,   144,    48,    49,    50,    51,    52,    38,   148,   149,
    48,    49,    50,    51,    52,    87,   150,   151,    94,    45,
    47,    42,    11,   147,    44,   155,    46,    45,    47,    42,
    59,    95,    44,    38,    46,   158,    48,    49,    50,    51,
    52,   132,   168,    60,    48,    49,    50,    51,    52,    45,
    47,    42,   113,    57,    44,   114,    46,    45,    47,   157,
    70,   177,    44,   178,    46,   180,    48,    49,    50,    51,
    52,   192,    58,   193,    48,    49,    50,    51,    52,    45,
    47,    42,    89,    57,    44,   202,    46,    45,    47,   210,
    96,   205,    44,   207,    46,   208,    48,    49,    50,    51,
    52,   214,    58,    97,    48,    49,    50,    51,    52,    45,
    47,    42,   113,   209,    44,   114,    46,    45,    47,   159,
   200,   211,    44,   201,    46,   224,    48,    49,    50,    51,
    52,   110,    60,   225,    48,    49,    50,    51,    52,    45,
    47,    42,   113,   227,    44,   114,    46,    45,    47,    42,
    89,   180,    44,   180,    46,   234,    48,    49,    50,    51,
    52,   251,   252,   253,    48,    49,    50,    51,    52,    45,
    47,    42,   113,   256,    44,   114,    46,    45,    47,    42,
   190,   259,    44,   262,    46,   224,    48,    49,    50,    51,
    52,   225,   189,   191,    48,    49,    50,    51,    52,    45,
    47,   175,   238,   263,    44,   237,    46,    45,    47,    42,
   231,   192,    44,   266,    46,   269,    48,    49,    50,    51,
    52,   270,   230,   232,    48,    49,    50,    51,    52,    45,
    47,   275,   242,   280,    44,   237,    46,    45,    47,   284,
   113,   285,    44,   114,    46,   286,    48,    49,    50,    51,
    52,   290,   292,   293,    48,    49,    50,    51,    52,   172,
   194,   170,   295,   296,   171,   297,   173,    45,    47,    42,
   300,   301,    44,   180,    46,   303,   195,   196,   197,   198,
   199,   304,   305,   281,    48,    49,    50,    51,    52,    45,
    47,    42,   306,   307,    44,   308,    46,    45,    47,    42,
   311,   312,    44,   313,    46,   314,    48,    49,    50,    51,
    52,   316,   317,   318,    48,    49,    50,    51,    52,    45,
    47,   319,   nil,   nil,    44,   nil,    46,    45,    47,    42,
    89,   nil,    44,   nil,    46,   nil,    48,    49,    50,    51,
    52,   nil,   nil,   nil,    48,    49,    50,    51,    52,    45,
    47,    42,    89,   nil,    44,   nil,    46,    45,    47,    42,
    89,   nil,    44,   nil,    46,   nil,    48,    49,    50,    51,
    52,   nil,   nil,   nil,    48,    49,    50,    51,    52,    45,
    47,    42,    11,   nil,    44,   nil,    46,    45,    47,    42,
    11,   nil,    44,    38,    46,   nil,    48,    49,    50,    51,
    52,    38,   nil,   nil,    48,    49,    50,    51,    52,    45,
    47,    42,   nil,   nil,    44,   nil,    46,    45,    47,   nil,
   nil,   nil,    44,   nil,    46,   nil,    48,    49,    50,    51,
    52,   nil,   nil,   nil,    48,    49,    50,    51,    52,    45,
    47,    42,   nil,   nil,    44,   nil,    46,    45,    47,    42,
   nil,   nil,    44,   nil,    46,   nil,    48,    49,    50,    51,
    52,   nil,   nil,   nil,    48,    49,    50,    51,    52,    45,
    47,    42,   nil,   nil,    44,   nil,    46,    45,    47,   273,
   nil,   nil,    44,   nil,    46,   nil,    48,    49,    50,    51,
    52,   nil,   nil,   nil,    48,    49,    50,    51,    52,    45,
    47,   274,   nil,   nil,    44,   nil,    46,    45,    47,   276,
   nil,   nil,    44,   nil,    46,   nil,    48,    49,    50,    51,
    52,   nil,   nil,   nil,    48,    49,    50,    51,    52,    45,
    47,    42,   nil,   nil,    44,   nil,    46,    45,    47,    42,
   nil,   nil,    44,   nil,    46,   nil,    48,    49,    50,    51,
    52,   nil,   nil,   nil,    48,    49,    50,    51,    52,    45,
    47,    42,   nil,   nil,    44,   nil,    46,    45,    47,    42,
   nil,   nil,    44,   nil,    46,   nil,    48,    49,    50,    51,
    52,   nil,   nil,   nil,    48,    49,    50,    51,    52,    45,
    47,    42,   nil,   nil,    44,   nil,    46,    45,    47,    42,
    11,   nil,    44,   nil,    46,   nil,    48,    49,    50,    51,
    52,    38,   nil,   nil,    48,    49,    50,    51,    52,    45,
    47,   315,   nil,   nil,    44,   nil,    46,   120,   248,   245,
   nil,   nil,   106,   nil,   247,   nil,    48,    49,    50,    51,
    52,   120,   248,   245,   249,   nil,   106,   nil,   247,   120,
   248,   245,   182,   184,   106,   nil,   247,   181,   249,   183,
   120,   248,   119,   nil,   nil,   106,   249,   247,   120,   248,
   310,   nil,   118,   106,   188,   247,   186,   249,   258,   187,
   nil,   120,   281,   119,   nil,   249,   106,   120,   123,   119,
   288,   120,   106,   119,   123,   nil,   106,   nil,   123,   120,
   110,   119,   nil,   120,   106,   119,   123,   nil,   106,   112,
   123,   113,   nil,   120,   114,   119,   nil,   120,   106,   119,
   123,   nil,   106,   nil,   123,   172,   169,   170,   nil,   120,
   171,   119,   173,   120,   106,   119,   123,   120,   106,   119,
   123,   120,   106,   119,   123,   120,   106,   119,   123,   120,
   106,   119,   123,   nil,   106,   nil,   123,   188,   271,   186,
   nil,   120,   187,   119,   272,   nil,   106,   nil,   123 ]

racc_action_check = [
     0,     0,     0,     0,    58,    94,     8,    58,    94,     0,
     0,     0,     0,     1,     0,     7,     0,     5,     0,     8,
     0,     7,    63,     0,    14,    16,     0,     0,     0,     0,
     0,    63,    63,    63,     7,     5,    63,     5,    63,    73,
    73,    17,   100,    18,   126,    19,    73,    24,    63,    63,
    63,    63,    63,   126,   126,   126,   100,   100,   126,    73,
   126,    54,    95,    54,    25,    95,    54,    68,    68,    26,
   126,   126,   126,   126,   126,    68,    68,    68,    68,    35,
    68,    53,    68,    35,    35,    35,    35,    66,    35,    68,
    35,    72,    68,    68,    68,    68,    68,    35,    75,    77,
    35,    35,    35,    35,    35,    36,    78,    79,    39,    36,
    36,    36,    36,    74,    36,    88,    36,    11,    11,    11,
    74,    39,    11,    36,    11,    92,    36,    36,    36,    36,
    36,    67,   101,    74,    11,    11,    11,    11,    11,    12,
    12,    12,    67,    91,    12,    67,    12,    29,    29,    91,
    29,   109,    29,   110,    29,   111,    12,    12,    12,    12,
    12,   117,    91,   118,    29,    29,    29,    29,    29,    38,
    38,    38,    38,   133,    38,   125,    38,    64,    64,   133,
    40,   127,    64,   130,    64,   131,    38,    38,    38,    38,
    38,   145,   133,    40,    64,    64,    64,    64,    64,    69,
    69,    69,   145,   132,    69,   145,    69,    70,    70,    93,
   123,   142,    70,   123,    70,   152,    69,    69,    69,    69,
    69,   210,    93,   153,    70,    70,    70,    70,    70,    71,
    71,    71,   210,   158,    71,   210,    71,    87,    87,    87,
    87,   160,    87,   162,    87,   163,    71,    71,    71,    71,
    71,   169,   178,   189,    87,    87,    87,    87,    87,    89,
    89,    89,   157,   202,    89,   157,    89,    90,    90,    90,
   115,   209,    90,   214,    90,   216,    89,    89,    89,    89,
    89,   218,   115,   115,    90,    90,    90,    90,    90,   105,
   105,   105,   166,   220,   105,   166,   105,   106,   106,   106,
   161,   228,   106,   230,   106,   234,   105,   105,   105,   105,
   105,   236,   161,   161,   106,   106,   106,   106,   106,   113,
   113,   243,   167,   251,   113,   167,   113,   119,   119,   254,
   224,   255,   119,   224,   119,   258,   113,   113,   113,   113,
   113,   262,   267,   268,   119,   119,   119,   119,   119,   120,
   120,   120,   271,   273,   120,   274,   120,   128,   128,   128,
   280,   281,   128,   283,   128,   284,   120,   120,   120,   120,
   120,   285,   288,   290,   128,   128,   128,   128,   128,   141,
   141,   141,   292,   293,   141,   295,   141,   143,   143,   143,
   300,   304,   143,   307,   143,   308,   141,   141,   141,   141,
   141,   311,   312,   313,   143,   143,   143,   143,   143,   144,
   144,   316,   nil,   nil,   144,   nil,   144,   146,   146,   146,
   146,   nil,   146,   nil,   146,   nil,   144,   144,   144,   144,
   144,   nil,   nil,   nil,   146,   146,   146,   146,   146,   147,
   147,   147,   147,   nil,   147,   nil,   147,   148,   148,   148,
   148,   nil,   148,   nil,   148,   nil,   147,   147,   147,   147,
   147,   nil,   nil,   nil,   148,   148,   148,   148,   148,   150,
   150,   150,   150,   nil,   150,   nil,   150,   151,   151,   151,
   151,   nil,   151,   150,   151,   nil,   150,   150,   150,   150,
   150,   151,   nil,   nil,   151,   151,   151,   151,   151,   156,
   156,   156,   nil,   nil,   156,   nil,   156,   211,   211,   nil,
   nil,   nil,   211,   nil,   211,   nil,   156,   156,   156,   156,
   156,   nil,   nil,   nil,   211,   211,   211,   211,   211,   212,
   212,   212,   nil,   nil,   212,   nil,   212,   213,   213,   213,
   nil,   nil,   213,   nil,   213,   nil,   212,   212,   212,   212,
   212,   nil,   nil,   nil,   213,   213,   213,   213,   213,   226,
   226,   226,   nil,   nil,   226,   nil,   226,   238,   238,   238,
   nil,   nil,   238,   nil,   238,   nil,   226,   226,   226,   226,
   226,   nil,   nil,   nil,   238,   238,   238,   238,   238,   242,
   242,   242,   nil,   nil,   242,   nil,   242,   245,   245,   245,
   nil,   nil,   245,   nil,   245,   nil,   242,   242,   242,   242,
   242,   nil,   nil,   nil,   245,   245,   245,   245,   245,   247,
   247,   247,   nil,   nil,   247,   nil,   247,   248,   248,   248,
   nil,   nil,   248,   nil,   248,   nil,   247,   247,   247,   247,
   247,   nil,   nil,   nil,   248,   248,   248,   248,   248,   249,
   249,   249,   nil,   nil,   249,   nil,   249,   260,   260,   260,
   nil,   nil,   260,   nil,   260,   nil,   249,   249,   249,   249,
   249,   nil,   nil,   nil,   260,   260,   260,   260,   260,   261,
   261,   261,   nil,   nil,   261,   nil,   261,   263,   263,   263,
   263,   nil,   263,   nil,   263,   nil,   261,   261,   261,   261,
   261,   263,   nil,   nil,   263,   263,   263,   263,   263,   310,
   310,   310,   nil,   nil,   310,   nil,   310,   168,   168,   168,
   nil,   nil,   168,   nil,   168,   nil,   310,   310,   310,   310,
   310,   270,   270,   270,   168,   nil,   270,   nil,   270,   275,
   275,   275,   112,   112,   275,   nil,   275,   112,   270,   112,
   296,   296,   296,   nil,   nil,   296,   275,   296,   297,   297,
   297,   nil,    59,   297,   114,   297,   114,   296,   208,   114,
   nil,    59,   252,    59,   nil,   297,    59,   208,    59,   208,
   259,   252,   208,   252,   208,   nil,   252,   nil,   252,   259,
    56,   259,   nil,    60,   259,    60,   259,   nil,    60,    56,
    60,    56,   nil,    96,    56,    96,   nil,    97,    96,    97,
    96,   nil,    97,   nil,    97,   103,   103,   103,   nil,   159,
   103,   159,   103,   190,   159,   190,   159,   191,   190,   191,
   190,   225,   191,   225,   191,   231,   225,   231,   225,   232,
   231,   232,   231,   nil,   232,   nil,   232,   237,   237,   237,
   nil,   253,   237,   253,   237,   nil,   253,   nil,   253 ]

racc_action_pointer = [
    -5,    13,   nil,   nil,   nil,    15,   nil,     4,   -11,   nil,
   nil,   103,   125,   nil,     4,   nil,    21,    19,    38,    28,
   nil,   nil,   nil,   nil,    27,    64,    69,   nil,   nil,   133,
   nil,   nil,   nil,   nil,   nil,    69,    95,   nil,   155,    91,
   163,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    81,    47,   nil,   785,   nil,   -12,   757,
   779,   nil,   nil,    17,   163,   nil,    82,   126,    61,   185,
   193,   215,    87,    29,   103,    88,   nil,    75,    79,    80,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   223,    89,   245,
   253,   132,    96,   192,   -11,    46,   789,   793,   nil,   nil,
    39,   119,   nil,   801,   nil,   275,   283,   nil,   nil,   140,
   148,   144,   728,   305,   750,   253,   nil,   150,   158,   313,
   335,   nil,   nil,   194,   nil,   146,    39,   176,   343,   nil,
   178,   168,   198,   162,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   365,   207,   373,   395,   186,   403,   425,   433,   nil,
   455,   463,   198,   206,   nil,   nil,   485,   246,   222,   805,
   230,   283,   232,   216,   nil,   nil,   276,   306,   703,   238,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   235,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   242,
   809,   813,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   252,   nil,   nil,   nil,   nil,   nil,   763,   254,
   216,   493,   515,   523,   268,   nil,   258,   nil,   264,   nil,
   266,   nil,   nil,   nil,   314,   817,   545,   nil,   290,   nil,
   292,   821,   825,   nil,   294,   nil,   298,   833,   553,   nil,
   nil,   nil,   575,   308,   nil,   583,   nil,   605,   613,   635,
   nil,   307,   767,   837,   300,   302,   nil,   nil,   330,   775,
   643,   665,   324,   673,   nil,   nil,   nil,   313,   314,   nil,
   717,   339,   nil,   340,   342,   725,   nil,   nil,   nil,   nil,
   344,   356,   nil,   352,   354,   360,   nil,   nil,   367,   nil,
   368,   nil,   371,   372,   nil,   369,   736,   744,   nil,   nil,
   377,   nil,   nil,   nil,   362,   nil,   nil,   364,   379,   nil,
   695,   385,   391,   392,   nil,   nil,   395,   nil,   nil,   nil ]

racc_action_default = [
  -177,  -177,    -1,    -2,    -3,    -4,    -5,    -6,    -7,    -8,
   -23,  -177,  -177,   -33,   -34,   -35,   -36,   -37,  -177,   -39,
   -40,   -41,   -42,   -43,  -177,   -52,   -54,   -55,   -56,  -177,
   -67,   -70,   -71,   -72,   -73,  -177,  -177,  -108,  -177,  -110,
  -111,  -112,  -129,  -130,  -131,  -132,  -133,  -134,  -135,  -136,
  -137,  -138,  -139,  -177,  -177,   -78,  -177,  -113,  -177,  -177,
  -177,   -24,   -44,  -177,  -177,   -74,  -177,  -177,  -177,   -58,
  -177,  -171,  -177,    -6,    -7,    -8,   -39,  -177,   -81,   -86,
   -87,   -88,   -90,   -91,   -92,   -93,   -94,  -177,  -177,  -177,
  -177,  -177,  -177,  -177,  -177,  -177,  -177,  -177,   320,    -9,
   -10,  -177,   -13,  -177,   -30,  -177,  -177,  -153,   -26,   -28,
  -177,  -127,  -177,  -177,  -177,  -177,   -27,   -29,  -177,  -177,
  -177,  -154,  -161,  -177,  -163,  -177,  -177,  -177,   -75,  -175,
  -177,  -103,  -177,    -6,   -50,   -51,   -52,   -53,   -54,   -57,
   -61,   -59,  -177,  -172,  -177,  -177,   -98,   -97,   -96,   -79,
  -177,  -177,    -6,    -7,   -95,   -80,  -177,  -177,  -177,  -177,
  -127,  -177,  -127,  -177,   -11,   -15,  -177,  -177,  -177,  -177,
  -148,  -149,  -150,  -151,  -146,  -152,  -147,  -115,   -47,   -62,
  -128,   -63,   -64,   -65,   -66,  -140,  -141,  -142,  -143,  -177,
  -177,  -177,  -121,   -48,  -155,  -156,  -157,  -158,  -159,  -160,
  -162,  -164,  -177,   -25,   -45,   -46,  -176,   -38,  -177,  -177,
  -177,  -177,  -173,   -76,  -177,  -101,  -177,  -100,  -177,   -99,
   -83,   -84,   -85,   -89,  -177,  -177,  -177,  -109,  -177,  -114,
  -177,  -177,  -177,  -118,  -177,   -16,  -177,  -177,  -177,  -144,
   -17,   -18,  -177,  -177,   -31,  -177,  -165,  -177,  -177,  -177,
  -170,  -177,  -177,  -116,  -177,  -177,  -122,  -102,  -177,  -177,
   -77,  -174,   -47,  -177,   -28,   -29,  -117,  -177,  -177,  -119,
  -177,  -177,  -145,  -177,  -177,  -177,  -169,  -166,  -167,  -168,
  -177,  -177,  -107,  -127,  -177,  -177,  -106,  -104,  -177,   -60,
  -177,   -82,  -177,  -177,   -20,  -177,  -177,  -177,   -12,   -32,
  -177,   -49,  -120,  -123,  -177,  -105,  -125,  -177,  -177,   -22,
  -177,  -177,  -177,  -177,   -21,   -19,  -177,  -124,  -126,   -14 ]

racc_goto_table = [
    71,   115,   179,    63,     7,   243,     8,     9,   223,   128,
   131,     5,   117,   125,    61,   221,   222,    14,    19,    24,
   246,     1,    69,    72,   235,   241,     2,    25,    26,    90,
   309,   309,   239,   239,     3,   129,     4,   160,   161,    77,
    88,    71,    91,     6,    93,    99,   100,   164,   101,   162,
   163,   229,   298,   233,   126,   102,   240,   104,   299,    13,
   140,    15,   143,   141,   142,    16,    17,    62,   134,   111,
    30,    31,   133,    32,     8,     9,   174,    33,    90,   135,
    90,   156,    34,   220,   185,   137,    19,   139,    92,   213,
   174,   152,    61,   153,     9,   136,   138,   176,   154,   107,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   294,   nil,   nil,
   nil,   nil,   228,   nil,   nil,   129,   nil,   203,   nil,   206,
   223,   nil,   246,   nil,   nil,   nil,   nil,   246,   291,   nil,
   nil,   nil,   140,   nil,   212,   nil,   nil,    90,    90,    90,
   nil,   nil,   nil,   254,   255,   nil,   nil,   226,   246,   246,
   215,   216,   216,   217,   218,   219,   260,   nil,   nil,   nil,
   nil,   257,   nil,   nil,   nil,   nil,   nil,   264,   nil,   nil,
   nil,   nil,   nil,   nil,   302,   nil,   nil,   nil,   265,   nil,
   nil,   nil,   129,   nil,   267,   268,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   261,   206,   282,   283,   nil,   nil,   185,
   nil,   nil,   287,   185,   nil,   nil,   174,   203,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   277,   278,
   279,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   206,   289,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   174 ]

racc_goto_check = [
    44,    23,    46,    22,     7,    14,     8,     9,    58,    52,
    23,     5,    25,    25,    21,    57,    57,    30,    34,    39,
    66,     1,    43,    53,    17,    17,     2,    41,    42,    22,
    20,    20,    24,    24,     3,    44,     4,    23,    23,    54,
    54,    44,     7,     6,     8,    10,    11,    12,    13,    25,
    25,    46,    15,    46,    22,    16,    18,    27,    28,    29,
    22,    31,    22,    43,    53,    32,    33,    38,    40,    45,
    47,    48,     7,    49,     8,     9,    44,    50,    22,     5,
    22,    22,    51,    56,    44,    30,    34,    39,    61,    52,
    44,     7,    21,     8,     9,    41,    42,    22,     5,    65,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    14,   nil,   nil,
   nil,   nil,    25,   nil,   nil,    44,   nil,    22,   nil,    22,
    58,   nil,    66,   nil,   nil,   nil,   nil,    66,    57,   nil,
   nil,   nil,    22,   nil,    22,   nil,   nil,    22,    22,    22,
   nil,   nil,   nil,    25,    25,   nil,   nil,    22,    66,    66,
     7,     7,     7,     8,     8,     9,    52,   nil,   nil,   nil,
   nil,    25,   nil,   nil,   nil,   nil,   nil,    23,   nil,   nil,
   nil,   nil,   nil,   nil,    46,   nil,   nil,   nil,    25,   nil,
   nil,   nil,    44,   nil,    25,    25,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    22,    22,    25,    25,   nil,   nil,    44,
   nil,   nil,    25,    44,   nil,   nil,    44,    22,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    22,    22,
    22,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    22,    22,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    44 ]

racc_goto_pointer = [
   nil,    21,    26,    34,    36,    11,    43,     4,     6,     7,
    -9,    -8,   -53,    -6,  -163,  -223,     1,  -142,  -111,   nil,
  -266,     3,    -9,   -57,  -134,   -47,   nil,     3,  -217,    59,
    17,    61,    65,    66,    18,   nil,   nil,   nil,    56,    19,
     0,    27,    28,    -7,   -29,    13,  -109,    70,    71,    73,
    77,    82,   -55,    -6,     4,   nil,   -67,  -135,  -143,   nil,
   nil,    50,   nil,   nil,   nil,    45,  -148,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,    84,   nil,    73,    74,    75,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   236,
   250,    10,    12,   109,   108,   nil,   116,   nil,   244,   nil,
    86,   nil,   nil,   nil,    76,    20,    21,    22,    23,   nil,
   nil,    85,   nil,   nil,    43,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    78,    79,    80,    81,    82,
    83,    37,    39,    40,    41,   121,   122,   124 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 41, :_reduce_6,
  1, 41, :_reduce_7,
  1, 41, :_reduce_8,
  3, 42, :_reduce_9,
  1, 46, :_reduce_none,
  2, 46, :_reduce_11,
  5, 47, :_reduce_12,
  1, 47, :_reduce_none,
  8, 52, :_reduce_14,
  1, 48, :_reduce_15,
  2, 48, :_reduce_16,
  2, 48, :_reduce_17,
  1, 54, :_reduce_none,
  5, 54, :_reduce_19,
  3, 53, :_reduce_20,
  5, 53, :_reduce_21,
  4, 53, :_reduce_22,
  1, 43, :_reduce_none,
  2, 43, :_reduce_24,
  4, 57, :_reduce_25,
  1, 59, :_reduce_none,
  1, 61, :_reduce_none,
  3, 44, :_reduce_28,
  3, 45, :_reduce_29,
  1, 49, :_reduce_none,
  1, 50, :_reduce_none,
  1, 51, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  4, 65, :_reduce_38,
  1, 66, :_reduce_39,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 70, :_reduce_none,
  2, 70, :_reduce_44,
  4, 74, :_reduce_45,
  4, 74, :_reduce_46,
  4, 71, :_reduce_47,
  4, 72, :_reduce_48,
  7, 73, :_reduce_49,
  3, 67, :_reduce_50,
  1, 75, :_reduce_none,
  1, 75, :_reduce_none,
  1, 75, :_reduce_none,
  1, 75, :_reduce_none,
  1, 75, :_reduce_none,
  1, 75, :_reduce_none,
  1, 76, :_reduce_none,
  2, 68, :_reduce_58,
  3, 68, :_reduce_59,
  5, 79, :_reduce_60,
  2, 79, :_reduce_61,
  4, 69, :_reduce_62,
  2, 81, :_reduce_63,
  2, 81, :_reduce_64,
  2, 81, :_reduce_65,
  2, 81, :_reduce_66,
  1, 40, :_reduce_none,
  1, 40, :_reduce_none,
  1, 40, :_reduce_none,
  1, 40, :_reduce_none,
  1, 40, :_reduce_none,
  1, 40, :_reduce_none,
  1, 40, :_reduce_none,
  2, 83, :_reduce_74,
  3, 87, :_reduce_75,
  4, 87, :_reduce_76,
  5, 87, :_reduce_77,
  2, 86, :_reduce_78,
  3, 84, :_reduce_79,
  3, 85, :_reduce_80,
  1, 90, :_reduce_81,
  5, 90, :_reduce_82,
  3, 90, :_reduce_83,
  3, 90, :_reduce_84,
  3, 90, :_reduce_85,
  1, 90, :_reduce_86,
  1, 90, :_reduce_87,
  1, 92, :_reduce_88,
  3, 92, :_reduce_89,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 95, :_reduce_none,
  1, 95, :_reduce_none,
  1, 95, :_reduce_none,
  2, 91, :_reduce_95,
  2, 93, :_reduce_96,
  2, 93, :_reduce_97,
  2, 93, :_reduce_98,
  3, 96, :_reduce_99,
  3, 96, :_reduce_100,
  3, 96, :_reduce_101,
  5, 78, :_reduce_102,
  3, 78, :_reduce_103,
  6, 78, :_reduce_104,
  7, 78, :_reduce_105,
  6, 78, :_reduce_106,
  6, 78, :_reduce_107,
  1, 77, :_reduce_none,
  4, 77, :_reduce_109,
  1, 97, :_reduce_110,
  1, 97, :_reduce_111,
  1, 97, :_reduce_112,
  2, 98, :_reduce_113,
  4, 99, :_reduce_114,
  4, 99, :_reduce_115,
  5, 99, :_reduce_116,
  5, 99, :_reduce_117,
  4, 100, :_reduce_118,
  5, 100, :_reduce_119,
  7, 100, :_reduce_120,
  4, 100, :_reduce_121,
  5, 100, :_reduce_122,
  7, 100, :_reduce_123,
  9, 100, :_reduce_124,
  7, 100, :_reduce_125,
  9, 100, :_reduce_126,
  0, 82, :_reduce_127,
  1, 82, :_reduce_none,
  1, 58, :_reduce_129,
  1, 58, :_reduce_none,
  1, 80, :_reduce_none,
  1, 80, :_reduce_none,
  1, 80, :_reduce_none,
  1, 80, :_reduce_none,
  1, 80, :_reduce_none,
  1, 80, :_reduce_none,
  1, 80, :_reduce_none,
  1, 80, :_reduce_none,
  1, 80, :_reduce_none,
  2, 60, :_reduce_140,
  2, 60, :_reduce_141,
  2, 60, :_reduce_142,
  2, 60, :_reduce_143,
  1, 55, :_reduce_none,
  2, 55, :_reduce_145,
  2, 101, :_reduce_146,
  2, 101, :_reduce_147,
  2, 101, :_reduce_148,
  2, 101, :_reduce_149,
  2, 101, :_reduce_150,
  2, 101, :_reduce_151,
  2, 63, :_reduce_none,
  1, 63, :_reduce_none,
  1, 102, :_reduce_none,
  2, 102, :_reduce_155,
  2, 102, :_reduce_156,
  2, 102, :_reduce_157,
  2, 102, :_reduce_158,
  2, 102, :_reduce_159,
  2, 102, :_reduce_160,
  1, 103, :_reduce_none,
  2, 103, :_reduce_162,
  1, 62, :_reduce_none,
  2, 62, :_reduce_164,
  1, 56, :_reduce_none,
  2, 56, :_reduce_166,
  2, 56, :_reduce_167,
  2, 56, :_reduce_168,
  2, 64, :_reduce_none,
  1, 64, :_reduce_none,
  1, 89, :_reduce_171,
  2, 89, :_reduce_172,
  3, 89, :_reduce_173,
  4, 89, :_reduce_174,
  1, 88, :_reduce_175,
  2, 88, :_reduce_176 ]

racc_reduce_n = 177

racc_shift_n = 320

racc_token_table = {
  false => 0,
  :error => 1,
  :T => 2,
  :Z => 3,
  :E => 4,
  :X => 5,
  :UNKNOWN => 6,
  :OPEN => 7,
  :LONGYEAR => 8,
  :UNMATCHED => 9,
  :DOTS => 10,
  :UA => 11,
  :PUA => 12,
  ":" => 13,
  "2" => 14,
  "4" => 15,
  "0" => 16,
  "-" => 17,
  "+" => 18,
  "1" => 19,
  "/" => 20,
  "3" => 21,
  "^" => 22,
  "[" => 23,
  "]" => 24,
  "{" => 25,
  "}" => 26,
  "," => 27,
  "(" => 28,
  ")" => 29,
  "-(" => 30,
  "5" => 31,
  "6" => 32,
  "7" => 33,
  "8" => 34,
  "9" => 35 }

racc_nt_base = 36

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "T",
  "Z",
  "E",
  "X",
  "UNKNOWN",
  "OPEN",
  "LONGYEAR",
  "UNMATCHED",
  "DOTS",
  "UA",
  "PUA",
  "\":\"",
  "\"2\"",
  "\"4\"",
  "\"0\"",
  "\"-\"",
  "\"+\"",
  "\"1\"",
  "\"/\"",
  "\"3\"",
  "\"^\"",
  "\"[\"",
  "\"]\"",
  "\"{\"",
  "\"}\"",
  "\",\"",
  "\"(\"",
  "\")\"",
  "\"-(\"",
  "\"5\"",
  "\"6\"",
  "\"7\"",
  "\"8\"",
  "\"9\"",
  "$start",
  "edtf",
  "level_0_expression",
  "level_1_expression",
  "level_2_expression",
  "date",
  "date_time",
  "year",
  "year_month",
  "year_month_day",
  "time",
  "base_time",
  "zone_offset",
  "hour",
  "minute",
  "second",
  "midnight",
  "zone_offset_hour",
  "positive_zone_offset",
  "d01_13",
  "d01_59",
  "positive_year",
  "digit",
  "month",
  "d01_12",
  "day",
  "d01_31",
  "d00_23",
  "d00_59",
  "unknown",
  "unspecified",
  "level_1_interval",
  "long_year_simple",
  "season",
  "unspecified_year",
  "unspecified_month",
  "unspecified_day",
  "unspecified_day_and_month",
  "positive_unspecified_year",
  "level_1_start",
  "level_1_end",
  "partial_uncertain_or_approximate",
  "partial_unspecified",
  "long_year",
  "positive_digit",
  "season_number",
  "ua",
  "season_qualified",
  "choice_list",
  "inclusive_list",
  "date_and_calendar",
  "long_year_scientific",
  "integer",
  "int1_4",
  "list",
  "earlier",
  "list_elements",
  "later",
  "list_element",
  "atomic",
  "consecutives",
  "pua_base",
  "pua_year",
  "pua_year_month",
  "pua_year_month_day",
  "d01_23",
  "d01_29",
  "d01_30" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

module_eval(<<'.,.,', 'parser.y', 23)
  def _reduce_6(val, _values, result)
     result = Date.new(val[0]).year_precision!
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 24)
  def _reduce_7(val, _values, result)
     result = Date.new(*val.flatten).month_precision!
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 25)
  def _reduce_8(val, _values, result)
     result = Date.new(*val.flatten).day_precision!
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 30)
  def _reduce_9(val, _values, result)
        result = DateTime.new(val[0].year, val[0].month, val[0].day, *val[2])
    result.skip_timezone = (val[2].length == 3)

    result
  end
.,.,

# reduce 10 omitted

module_eval(<<'.,.,', 'parser.y', 35)
  def _reduce_11(val, _values, result)
     result = val.flatten
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 37)
  def _reduce_12(val, _values, result)
     result = val.values_at(0, 2, 4)
    result
  end
.,.,

# reduce 13 omitted

module_eval(<<'.,.,', 'parser.y', 40)
  def _reduce_14(val, _values, result)
     result = [24, 0, 0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 42)
  def _reduce_15(val, _values, result)
     result = 0
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 43)
  def _reduce_16(val, _values, result)
     result = -1 * val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 44)
  def _reduce_17(val, _values, result)
     result = val[1]
    result
  end
.,.,

# reduce 18 omitted

module_eval(<<'.,.,', 'parser.y', 48)
  def _reduce_19(val, _values, result)
     result = 0
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 52)
  def _reduce_20(val, _values, result)
     result = Rational(val[0] * 60 + val[2], 1440)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 53)
  def _reduce_21(val, _values, result)
     result = Rational(840, 1440)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 54)
  def _reduce_22(val, _values, result)
     result = Rational(val[3], 1440)
    result
  end
.,.,

# reduce 23 omitted

module_eval(<<'.,.,', 'parser.y', 58)
  def _reduce_24(val, _values, result)
     result = -val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 61)
  def _reduce_25(val, _values, result)
        result = val.zip([1000,100,10,1]).reduce(0) { |s,(a,b)| s += a * b }

    result
  end
.,.,

# reduce 26 omitted

# reduce 27 omitted

module_eval(<<'.,.,', 'parser.y', 67)
  def _reduce_28(val, _values, result)
     result = [val[0], val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 74)
  def _reduce_29(val, _values, result)
        result = val[0] << val[2]
    if result[2] > 31 || (result[2] > 30 && [2,4,6,9,11].include?(result[1])) || (result[2] > 29 && result[1] == 2)
      raise ArgumentError, "invalid date (invalid days #{result[2]} for month #{result[1]})"
    end

    result
  end
.,.,

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

module_eval(<<'.,.,', 'parser.y', 93)
  def _reduce_38(val, _values, result)
     result = EDTF::Unknown.new
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 99)
  def _reduce_39(val, _values, result)
                    result = Date.new(val[0][0]).year_precision!
                result.unspecified.year[2,2] = val[0][1]

    result
  end
.,.,

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

module_eval(<<'.,.,', 'parser.y', 110)
  def _reduce_44(val, _values, result)
                         result = val[1]
                     result[0] = -result[0]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 117)
  def _reduce_45(val, _values, result)
          result = [val[0,3].zip([1000,100,10]).reduce(0) { |s,(a,b)| s += a * b }, [false,true]]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 121)
  def _reduce_46(val, _values, result)
          result = [val[0,2].zip([1000,100]).reduce(0) { |s,(a,b)| s += a * b }, [true, true]]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 125)
  def _reduce_47(val, _values, result)
        result = Date.new(val[0]).unspecified!(:month)
    result.precision = :month

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 130)
  def _reduce_48(val, _values, result)
        result = Date.new(*val[0]).unspecified!(:day)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 134)
  def _reduce_49(val, _values, result)
        result = Date.new(val[0]).unspecified!([:day,:month])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 139)
  def _reduce_50(val, _values, result)
        result = Interval.new(val[0], val[2])

    result
  end
.,.,

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

module_eval(<<'.,.,', 'parser.y', 150)
  def _reduce_58(val, _values, result)
          result = Date.new(val[1])
      result.precision = :year

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 155)
  def _reduce_59(val, _values, result)
          result = Date.new(-1 * val[2])
      result.precision = :year

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 162)
  def _reduce_60(val, _values, result)
          result = val.zip([10000,1000,100,10,1]).reduce(0) { |s,(a,b)| s += a * b }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 164)
  def _reduce_61(val, _values, result)
     result = 10 * val[0] + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 169)
  def _reduce_62(val, _values, result)
        result = Season.new(val[0], val[2])
    val[3].each { |ua| result.send(ua) }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 173)
  def _reduce_63(val, _values, result)
     result = 21
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 174)
  def _reduce_64(val, _values, result)
     result = 22
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 175)
  def _reduce_65(val, _values, result)
     result = 23
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 176)
  def _reduce_66(val, _values, result)
     result = 24
    result
  end
.,.,

# reduce 67 omitted

# reduce 68 omitted

# reduce 69 omitted

# reduce 70 omitted

# reduce 71 omitted

# reduce 72 omitted

# reduce 73 omitted

module_eval(<<'.,.,', 'parser.y', 193)
  def _reduce_74(val, _values, result)
     result = val[0]; result.qualifier = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 199)
  def _reduce_75(val, _values, result)
          result = Date.new(val[0].year * 10 ** val[2]).year_precision!

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 203)
  def _reduce_76(val, _values, result)
          result = Date.new(val[1] * 10 ** val[3]).year_precision!

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 207)
  def _reduce_77(val, _values, result)
          result = Date.new(-1 * val[2] * 10 ** val[4]).year_precision!

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 212)
  def _reduce_78(val, _values, result)
     result = val[0]; result.calendar = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 214)
  def _reduce_79(val, _values, result)
     result = val[1].choice!
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 216)
  def _reduce_80(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 218)
  def _reduce_81(val, _values, result)
     result = EDTF::Set.new(val[0]).earlier!
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 219)
  def _reduce_82(val, _values, result)
     result = EDTF::Set.new([val[0]] + val[2] + [val[4]]).earlier!.later!
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 220)
  def _reduce_83(val, _values, result)
     result = EDTF::Set.new([val[0]] + val[2]).earlier!
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 221)
  def _reduce_84(val, _values, result)
     result = EDTF::Set.new([val[0]] + [val[2]]).earlier!.later!
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 222)
  def _reduce_85(val, _values, result)
     result = EDTF::Set.new(val[0] + [val[2]]).later!
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 223)
  def _reduce_86(val, _values, result)
     result = EDTF::Set.new(*val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 224)
  def _reduce_87(val, _values, result)
     result = EDTF::Set.new(val[0]).later!
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 227)
  def _reduce_88(val, _values, result)
     result = [val[0]].flatten
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 228)
  def _reduce_89(val, _values, result)
     result = val[0] + [val[2]].flatten
    result
  end
.,.,

# reduce 90 omitted

# reduce 91 omitted

# reduce 92 omitted

# reduce 93 omitted

# reduce 94 omitted

module_eval(<<'.,.,', 'parser.y', 240)
  def _reduce_95(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 242)
  def _reduce_96(val, _values, result)
     result = Date.new(*val[0]).day_precision!
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 243)
  def _reduce_97(val, _values, result)
     result = Date.new(*val[0]).month_precision!
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 244)
  def _reduce_98(val, _values, result)
     result = Date.new(val[0]).year_precision!
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 247)
  def _reduce_99(val, _values, result)
     result = (Date.new(val[0]).day_precision! .. Date.new(val[2]).day_precision!)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 248)
  def _reduce_100(val, _values, result)
     result = (Date.new(val[0]).month_precision! .. Date.new(val[2]).month_precision!)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 249)
  def _reduce_101(val, _values, result)
     result = (Date.new(val[0]).year_precision! .. Date.new(val[2]).year_precision!)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 255)
  def _reduce_102(val, _values, result)
          result = Date.new(val[0][0], val[2], val[4])
      result.unspecified.year[2,2] = val[0][1]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 260)
  def _reduce_103(val, _values, result)
          result = Date.new(val[0][0], val[2], 1)
      result.month_precision!
      result.unspecified.year[2,2] = val[0][1]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 266)
  def _reduce_104(val, _values, result)
          result = Date.new(val[0][0], 1, val[5])
      result.unspecified.year[2,2] = val[0][1]
      result.unspecified!(:month)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 272)
  def _reduce_105(val, _values, result)
          result = Date.new(val[0][0], 1, 1)
      result.unspecified.year[2,2] = val[0][1]
      result.unspecified!([:month, :day])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 278)
  def _reduce_106(val, _values, result)
          result = Date.new(val[0][0], val[2], 1)
      result.unspecified.year[2,2] = val[0][1]
      result.unspecified!(:day)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 284)
  def _reduce_107(val, _values, result)
          result = Date.new(val[0], 1, val[5])
      result.unspecified!(:month)

    result
  end
.,.,

# reduce 108 omitted

module_eval(<<'.,.,', 'parser.y', 291)
  def _reduce_109(val, _values, result)
     result = uoa(val[1], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 294)
  def _reduce_110(val, _values, result)
     result = val[0].year_precision!
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 295)
  def _reduce_111(val, _values, result)
     result = val[0][0].month_precision!
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 296)
  def _reduce_112(val, _values, result)
     result = val[0].day_precision!
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 298)
  def _reduce_113(val, _values, result)
     result = uoa(Date.new(val[0]), val[1], :year)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 302)
  def _reduce_114(val, _values, result)
          result = [uoa(val[0].change(:month => val[2]), val[3], [:month, :year])]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 305)
  def _reduce_115(val, _values, result)
            result = [uoa(Date.new(val[0], val[2]), val[3], [:year, :month])]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 308)
  def _reduce_116(val, _values, result)
            result = [uoa(Date.new(val[0], val[2]), val[4], [:month]), true]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 311)
  def _reduce_117(val, _values, result)
            result = [uoa(val[0].change(:month => val[2]), val[4], [:month]), true]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 317)
  def _reduce_118(val, _values, result)
          result = uoa(val[0][0].change(:day => val[2]), val[3], val[0][1] ? [:day] : nil)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 320)
  def _reduce_119(val, _values, result)
            result = uoa(val[0][0].change(:day => val[2]), val[4], [:day])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 323)
  def _reduce_120(val, _values, result)
            result = uoa(uoa(Date.new(val[0], val[2], val[5]), val[4], :month), val[6], :day)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 326)
  def _reduce_121(val, _values, result)
            result = uoa(Date.new(val[0][0], val[0][1], val[2]), val[3])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 329)
  def _reduce_122(val, _values, result)
            result = uoa(Date.new(val[0][0], val[0][1], val[2]), val[4], [:day])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 332)
  def _reduce_123(val, _values, result)
            result = uoa(Date.new(val[0], val[2], val[4]), val[6], [:month, :day])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 335)
  def _reduce_124(val, _values, result)
            result = Date.new(val[0], val[2], val[4])
        result = uoa(result, val[6], [:day])
        result = uoa(result, val[8], [:month, :day])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 340)
  def _reduce_125(val, _values, result)
            result = val[0].change(:month => val[2], :day => val[4])
        result = uoa(result, val[6], [:month, :day])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 344)
  def _reduce_126(val, _values, result)
            result = val[0].change(:month => val[2], :day => val[4])
        result = uoa(result, val[6], [:day])
        result = uoa(result, val[8], [:month, :day])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 355)
  def _reduce_127(val, _values, result)
     result = []
    result
  end
.,.,

# reduce 128 omitted

module_eval(<<'.,.,', 'parser.y', 359)
  def _reduce_129(val, _values, result)
     result = 0
    result
  end
.,.,

# reduce 130 omitted

# reduce 131 omitted

# reduce 132 omitted

# reduce 133 omitted

# reduce 134 omitted

# reduce 135 omitted

# reduce 136 omitted

# reduce 137 omitted

# reduce 138 omitted

# reduce 139 omitted

module_eval(<<'.,.,', 'parser.y', 365)
  def _reduce_140(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 366)
  def _reduce_141(val, _values, result)
     result = 10
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 367)
  def _reduce_142(val, _values, result)
     result = 11
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 368)
  def _reduce_143(val, _values, result)
     result = 12
    result
  end
.,.,

# reduce 144 omitted

module_eval(<<'.,.,', 'parser.y', 372)
  def _reduce_145(val, _values, result)
     result = 13
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 375)
  def _reduce_146(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 376)
  def _reduce_147(val, _values, result)
     result = 10 + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 377)
  def _reduce_148(val, _values, result)
     result = 20
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 378)
  def _reduce_149(val, _values, result)
     result = 21
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 379)
  def _reduce_150(val, _values, result)
     result = 22
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 380)
  def _reduce_151(val, _values, result)
     result = 23
    result
  end
.,.,

# reduce 152 omitted

# reduce 153 omitted

# reduce 154 omitted

module_eval(<<'.,.,', 'parser.y', 388)
  def _reduce_155(val, _values, result)
     result = 24
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 389)
  def _reduce_156(val, _values, result)
     result = 25
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 390)
  def _reduce_157(val, _values, result)
     result = 26
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 391)
  def _reduce_158(val, _values, result)
     result = 27
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 392)
  def _reduce_159(val, _values, result)
     result = 28
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 393)
  def _reduce_160(val, _values, result)
     result = 29
    result
  end
.,.,

# reduce 161 omitted

module_eval(<<'.,.,', 'parser.y', 397)
  def _reduce_162(val, _values, result)
     result = 30
    result
  end
.,.,

# reduce 163 omitted

module_eval(<<'.,.,', 'parser.y', 401)
  def _reduce_164(val, _values, result)
     result = 31
    result
  end
.,.,

# reduce 165 omitted

module_eval(<<'.,.,', 'parser.y', 405)
  def _reduce_166(val, _values, result)
     result = 30 + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 406)
  def _reduce_167(val, _values, result)
     result = 40 + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 407)
  def _reduce_168(val, _values, result)
     result = 50 + val[1]
    result
  end
.,.,

# reduce 169 omitted

# reduce 170 omitted

module_eval(<<'.,.,', 'parser.y', 414)
  def _reduce_171(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 415)
  def _reduce_172(val, _values, result)
     result = 10 * val[0] + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 418)
  def _reduce_173(val, _values, result)
               result = val.zip([100,10,1]).reduce(0) { |s,(a,b)| s += a * b }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 422)
  def _reduce_174(val, _values, result)
               result = val.zip([1000,100,10,1]).reduce(0) { |s,(a,b)| s += a * b }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 426)
  def _reduce_175(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 427)
  def _reduce_176(val, _values, result)
     result = 10 * val[0] + val[1]
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module EDTF
